### ISSUE TITLE
Update release on Cocoapods

### ISSUE THREAD

**Issue by souzainf3** [facebook/pop#259]
Update release distributed in cocoapods

**Comment by iantheparker** [comment]
I just updated my cocoapods to 0.38.2 and I got this error:

[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

Now I've got a bajillion compiler errors everywhere there was a lovely pop animation :(

**Comment by grp** [comment]
@iantheparker That seems like it's related to a Cocoapods update (and more specifically, a very reasonable conflict between build settings between pods). I'd suggest comparing the value of the build setting it noted between those Pods and sending pull requests as appropriate to make them match, but it's hard to say for your specific case.

@souzainf3  Thanks for filing. We'll look into updating the Cocoapod, but generally you can track master without too many issues rather than a specific version.
