### ISSUE TITLE
Updating toValue continuously doesn't make for smooth animation

### ISSUE THREAD

**Issue by tettoffensive** [facebook/pop#265]
I have an animation of with `kPOPScrollViewContentOffset` where I am continuously updating the toValue based on new input. Since it's happening over and over again, sometimes this new value is really close to the current running animation, but others it is wildly different.

It seems that my current way of just using `pop_animationForKey` to see if there's already an animation and then updating it's `toValue` doesn't seem to work as I'd hoped. I suppose maybe it's not meant to continuously update or be set to values that are very close to each other?

I do see that the progress attribute seems to get reset fairly close to zero each time I update the toValue. (I've tried both springs and basic)

Is there a better way to do something like this already in place?

**Comment by grp** [comment]
This depends on what animation type you're using. With a spring animation, what you described should work correctly: it will retarget the spring to the new toValue and smoothly transition the velocity towards that target. With a basic animation, it will just restart the animation from the current position, since there's not generally a way to retarget the explicit curves.

The progress will always reset, though. (This is one of the reasons that we don't recommend using progress.)

**Comment by grp** [comment]
If you post a quick sample project showing the issue, I could look into it more.
