### ISSUE TITLE
Set animation fraction/progress

### ISSUE THREAD

**Issue by zdenektopic** [facebook/pop#331]
Is it possible to create an animation and manually set its progress?

Just like in new animation API in iOS 10.

**Comment by grp** [comment]
Generally, you wouldn't need Pop to set a property to a specific progress, since you could just set the property directly. For example, to fade in a view, just set `view.alpha = progress;`. If you want to adjust the property every frame, `POPCustomAnimation` (a wrapper over `CADisplayLink`) might be useful.
